# Generated by Django 3.1.2 on 2020-10-29 17:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20201029_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Адрес доставки')),
                ('status', models.CharField(choices=[('new', 'новый заказ'), ('in_progress', 'заказ в обработке'), ('is_ready', 'заказ готов'), ('completed', 'заказ выполнен')], default='new', max_length=70, verbose_name='Статус заказа')),
                ('buying_type', models.CharField(choices=[('self', 'самовывоз'), ('delivery', 'доставка')], default='self', max_length=70, verbose_name='Тип заказа')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата получения заказа')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='MainApp.customer', verbose_name='Покупатель')),
            ],
            options={
                'ordering': ('created_date', 'order_date'),
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_customer', to='MainApp.Order', verbose_name='Заказы покупателя'),
        ),
    ]
