# Generated by Django 3.1.2 on 2020-10-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_notebookproduct_smartphoneproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebookproduct',
            name='image',
            field=models.ImageField(upload_to='notebooks', verbose_name='Изображение ноутбука'),
        ),
        migrations.AlterField(
            model_name='smartphoneproduct',
            name='image',
            field=models.ImageField(upload_to='smartphones', verbose_name='Изображение смартфона'),
        ),
    ]
