# Generated by Django 3.1.2 on 2020-10-25 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20201025_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='MainApp.cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='smartphoneproduct',
            name='sd_max_volume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальный объем встраиваемой памяти'),
        ),
    ]
