# Generated by Django 3.1.2 on 2020-10-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20201025_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphoneproduct',
            name='sd_max_volume',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=255, null=True, verbose_name='Максимальный объем SD карты'),
        ),
    ]
