# Generated by Django 3.1.2 on 2020-10-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_auto_20201026_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphoneproduct',
            name='sd_max_volume',
            field=models.CharField(blank=True, choices=[('2', '2 GB'), ('4', '4 GB'), ('6', '6 GB'), ('8', '8 GB'), ('16', '16 GB')], max_length=255, null=True, verbose_name='Максимальный объем SD карты'),
        ),
    ]
